version: "3"

services:

    db:
        image: mysql:5.7 
        restart: always
        ports:
            - '3306:3306'
        environment: 
            MYSQL_DATABASE: db_counts
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - db_data:/var/lib/mysql
        networks: 
            - default
    adminer:
        image: adminer
        restart: always
        ports:
            - 9000:8080            
volumes:
    db_data: